### ISSUE TITLE
Invalid prop `customLabels` of type `object` supplied to `ReactFlagsSelect`

### ISSUE THREAD

**Issue by kasongoyo** [ekwonye-richard/react-flags-select#11]
Invalid prop `customLabels` of type `object` supplied to `ReactFlagsSelect`, expected `array`. This error is coming out because from the doc you specified customLabel as object while in the code you have set it's prop type as object. Please update the code accordingly

**Comment by ekwonye-richard** [comment]
Thanks @kasongoyo, a fix has been publish.
The correct type is object.

Please install the latest version from npm..
