### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by napomj** [ekwonye-richard/react-flags-select#120]
Can there be a styling option to remove the border for the select box?

![Screen Shot 2021-10-05 at 9 44 12 AM](https://user-images.githubusercontent.com/61099489/136066460-21f6e860-7571-4dbd-9cde-42dc50d6be52.png)

In v1 it was like this:

![Screen Shot 2021-10-05 at 9 46 00 AM](https://user-images.githubusercontent.com/61099489/136066715-f119d917-369e-4c97-9411-c0f688cdee7a.png)

Thanks!

**Comment by v4dkou** [comment]
@napomj There's a prop named "selectButtonClassName" that can be used for this
