### ISSUE TITLE
How to use blacklistCountries

### ISSUE THREAD

**Issue by emrecan-balgun** [ekwonye-richard/react-flags-select#125]
First of all, thank you for the module, it will be very useful to me.

I'm sorry. I couldn't use the country part of the blacklist.

For example, I want to add the country with the code 'AS' to the blacklist, but I don't know how to do it.

**Comment by ekwonye-richard** [comment]
Hi @emrecan-balgun, you check it out here https://github.com/ekwonye-richard/react-flags-select#blacklistcountries
