### ISSUE TITLE
Button id is not changeable

### ISSUE THREAD

**Issue by itamarmoa** [ekwonye-richard/react-flags-select#145]
The div id is changeable, but the button isn't so if there are 2 flags selectors, it causes this alert on browser
```
[DOM] Found 2 elements with non-unique id #rfs-btn: (More info: https://goo.gl/9p2vKq) <button id=​"rfs-btn" type=​"button" class=​"ReactFlagsSelect-module_selectBtn__19wW7 flag-select-button" aria-labelledby=​"rfs-btn" aria-haspopup=​"listbox" aria-expanded=​"false" data-testid=​"rfs-btn" style=​"font-size:​ 16px;​">​…​</button>​ flex 
```

**Comment by ekwonye-richard** [comment]
Hi @itamarmoa 

This issue has been fixed in this [PR](https://github.com/ekwonye-richard/react-flags-select/pull/151/files).

You can use the `rfsKey` to have unique ids.
