### ISSUE TITLE
React v16 support?

### ISSUE THREAD

**Issue by GrzegorzZajac000** [ekwonye-richard/react-flags-select#17]
Can I expect to add support for react 16?

**Comment by ekwonye-richard** [comment]
Hello @GrzegorzZajac000 
Sorry for the late response.

I'm working on a migration to React 16. This will be pushed soon

**Comment by pixelass** [comment]
@ekwonye-richard can you define "soon"?

**Comment by zedtux** [comment]
@ekwonye-richard can you please push your migration to React 16 😇

**Comment by ekwonye-richard** [comment]
React 16 us now very much supported in v2
