### ISSUE TITLE
All SVG flags are included during build

### ISSUE THREAD

**Issue by fonsleenaars** [ekwonye-richard/react-flags-select#22]
Thanks for making this useful library.

I was running into an issue I can't quite seem to debug. I'm using your package in one of the described use cases: a static list of countries should be available in the dropdown.

```js
// Unicode language subtags I want available
const languages = ['cs', 'de', 'en', 'es', 'fr', 'it', 'ja', 'ko', 'pl', 'ru', 'uk', 'zh'];
// Language codes as defined by react-flags-select, along with their language
const languageCodes = {
  cs: ['CZ', 'čeština'],
  de: ['DE', 'Deutsche'],
  en: ['GB', 'English'],
  es: ['ES', 'Español'],
  fr: ['FR', 'Français'],
  it: ['IT', 'Italiano'],
  ja: ['JP', '日本人'],
  ko: ['KR', '한국어'],
  pl: ['PL', 'Polskie'],
  ru: ['RU', 'русский'],
  uk: ['UA', 'Українська'],
  zh: ['CN', '中文'],
};
// Create an array from the unicode subtags to the react-flags-select tags:
const countries = languages.map(language => languageCodes[language][0]);
// Also create a mapping of the custom labels
const countryLabels = Object.values(languageCodes).reduce((acc, [code, label]) => {
  acc[code] = label;
  return acc;
}, {});
...
...
...
<ReactFlagsSelect
    alignOptions="left"
    className={styles.language}
    countries={countries}
    customLabels={countryLabels}
    defaultCountry={languageCodes[language][0]}
    onSelect={this.onSelect}
/>
```

As it stands, when I run my build I end up with *all* of the SVG files in the `flags` folder in my `dist` folder. I looked at your code and from what I can see you dynamically require the SVG files. I also checked that the `countries` in your `this.state.countries` only includes my list of countries during runtime.

I'm not quite sure why all the SVGs end up in my `dist` folder and thought perhaps you had run into this before. I'm using webpack 4+ as my bundler with a pretty standard setup (can paste if necessary).

Thanks!

**Comment by velchevski** [comment]
@fonsleenaars I am having the same issue. Also using Webpack 4.

**Comment by Deathlive** [comment]
Has anyone found a normal solution to this problem?

`
WARNING in ./node_modules/react-flags-select/flags/th.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <svg width="514" height="334" viewBox="0 0 514 334" xmlns="http://www.w3.org/2000/svg">
|   <g stroke="#000" fill="none">
|     <path fill="#A51931" d="M1 1h512v57H1z"/>
`

**Comment by fonsleenaars** [comment]
> Has anyone found a normal solution to this problem?
> 
> > WARNING in ./node_modules/react-flags-select/flags/th.svg 1:0
> > Module parse failed: Unexpected token (1:0)
> > You may need an appropriate loader to handle this file type.

Do you have webpack handling your SVG files if you're using them in your code?

For example:
```js
{
    test: /\.(gif|jpe?g|png|svg)(\?.*)?$/,
    use: [
    'file-loader',
    'image-webpack-loader',
    ],
},
```

**Comment by Deathlive** [comment]
@fonsleenaars 
Yes, i have **url-loader**

`      {
        test: /\.(gif|png|jpg|jpeg)$/,
        exclude: /node_modules/,
        include: path.resolve(__dirname, './src/client/assets/images'),
        use: {
          loader: 'url-loader',
          options: {
            limit: 22000,
            name: 'assets/[name]-[hash].[ext]'
          }
        }
      }`

**Comment by fonsleenaars** [comment]
Your setup wouldn't handle `node_modules`, as they're excluded in that config though. It looks like your setup is pulling from `src/client/assets/images`. 

You could try setting up a loader just for `node_modules` / `svg` files, to see if you can get it working, which would also immediately make clear that this is an issue this library should address ;)

**Comment by Deathlive** [comment]
@fonsleenaars 
For the test case, I deleted exlude and include.
Аnd it worked
Thanks

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 which now renders the flags as SVGs
