### ISSUE TITLE
does not work correctly with a modal window

### ISSUE THREAD

**Issue by gabos31** [ekwonye-richard/react-flags-select#23]
if the component is located on a modal window, then after selecting the country, the dropdown does not disappear.

**Comment by antoniojps** [comment]
This might be an issue caused by a specific code/style in your modal.
Can you provide more information, for example the code of your modal component?

**Comment by fedecryto** [comment]
I'm using a simple Bootstrap Modal... Somehow toggleOptions method is not being called.
@gabos31 if you need a quick workaround, you could force toggleOptions by doing:
  ```
const inputEl = useRef();

  const _selectCountry = countryCode=> {
    ...
    inputEl.current.toggleOptions();
  };

 return (
        <ReactFlagsSelect
          ref={inputEl}
           onSelect={_selectCountry}
        />
  );
```

But there is still one problem: if you click outside the dropdown... it won't close... :(
To solve that, that 'workaround' becomes a horrible code
