### ISSUE TITLE
Unexpected token in every .svg file.

### ISSUE THREAD

**Issue by MattiaVorstenbosch** [ekwonye-richard/react-flags-select#34]
Awesome library, however I'm having issues getting it to work. First of all i'd like to bring to your attention that travis CI reports the build is failing. https://travis-ci.org/ekwonye-richard/react-flags-select

In addition, In every .svg file there seems to be an Unexpected token, it throws the following error for each svg:

```sh
WARNING in ./node_modules/react-flags-select/flags/zw.svg
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/User/Documents/react-template/node_modules/react-flags-select/flags/zw.svg: Unexpected token (10:9)
```

Anyone else experiencing this issue?

I tried running the demo on React v16+ and it won't run. Is it possible the library is not compatible with v16?

**Comment by MattiaVorstenbosch** [comment]
Important to note here:

![actual error](https://user-images.githubusercontent.com/33621526/62713371-eb2cf500-b9fc-11e9-84f9-5899d4add2fc.png)

**Comment by spitchaiah** [comment]
Even I'm unable to get this library working using the React v16 version.

**Comment by ekwonye-richard** [comment]
Hi @spitchaiah I'm working on a new version of this Library that resolves most of this issues. 🙏🏾

**Comment by ekwonye-richard** [comment]
Hi @MattiaVorstenbosch I'm working on a new version of this Library that resolves most of this issues. 🙏🏾

**Comment by chguerra** [comment]
I'm still having this issue using React 16.8.6. This only happens when you use the prop defaultCountry. Never happens if this option is not set.

**Comment by kodcuserkan** [comment]
16.13.1 and still having same trouble

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 which now renders the flags as SVGs
