### ISSUE TITLE
None of the flag icons are not displaying in the select dropdown

### ISSUE THREAD

**Issue by spitchaiah** [ekwonye-richard/react-flags-select#35]
Hello Team,

Thanks for creating this library to display countries list along with their flag icons. I'm trying to get this 'react-flags-select' library working in our app but for some reason, in the select dropdown it only displays countries list and not the flag icons. I'm guessing I'm missing something basic here. Here's what i did so far:

1. npm install react-flags-select --save
2. In one of our components, imported this: `import ReactFlagsSelect from 'react-flags-select';
`
3. Have attached the screenshot of the select dropdown below.

![image](https://user-images.githubusercontent.com/6586533/63466289-fc302a00-c430-11e9-95f0-5683bd69da12.png)

**Chrome Dev Tools:**
1. On the chrome Dev tools under 'Source' tab (Page > webpack:// ), I could see the all svgs loaded but still the flag icons wont display. Also, I tried installing new svg loader from here https://www.npmjs.com/package/svg-inline-loader but still its not working.

![image](https://user-images.githubusercontent.com/6586533/63466898-41a12700-c432-11e9-8812-5736ff6c13c7.png)

2. Upon clicking the dropdown in the UI, on the network tab in Dev Tools, I see many URLs(i guess corresponding to countries) like this:

http://localhost:3000/payments/%3Csvg%20viewBox=%220%200%20512%20336%22%20xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg%20fill=%22none%22%3E%3Cpath%20d=%22M503.172%20335.724H8.828A8.829%208.829%200%200%201%200%20326.896V9.104A8.829%208.829%200%200%201%208.828.276h494.345a8.829%208.829%200%200%201%208.828%208.828v317.792a8.83%208.83%200%200%201-8.829%208.828z%22%20fill=%22

Configs:
Reactjs: 16.5.x
Webpack: 3.5.5
OS: Mac-Mojave

**Comment by spitchaiah** [comment]
Any inputs or suggestions please for this issue ? thanks!

**Comment by ekwonye-richard** [comment]
Hi @spitchaiah I'm working on a new version of this Library that resolves most of this issues. 🙏🏾

**Comment by spitchaiah** [comment]
Thanks much Richard for the update! Appreciate it.

**Comment by spitchaiah** [comment]
@ekwonye-richard : Any idea on when we can expect the fix for this issue? thank you!

**Comment by cipick** [comment]
@spitchaiah it seems to work with this loader https://github.com/bhovhannes/svg-url-loader

**Comment by dayoolacodes** [comment]
has this been fixed?

**Comment by dayoolacodes** [comment]
Hello Richard, Pls has this been fixed?

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 which now renders the flags as SVGs
