### ISSUE TITLE
Directly render the options

### ISSUE THREAD

**Issue by lorenzosfarra** [ekwonye-richard/react-flags-select#36]
Hi,

as far as I can see there is no way to automatically open the options, but only clicking on the `country-label` span.
In my use case I should render this element directly in a modal....and it should be already displaying the options (I see that it depends on the `openOptions` state param), without clicking anything.
Is it something possible, now or in the near future?

Thanks in advance!
  Lorenzo

**Comment by ekwonye-richard** [comment]
We don't have this support as a Select dropdown needs to be triggered by a user interaction
