### ISSUE TITLE
SyntaxError: Unexpected token < /node_modules/react-flags-select/flags/us.svg:1

### ISSUE THREAD

**Issue by umkhan65** [ekwonye-richard/react-flags-select#42]
I'm using this package in my next.js application. I had no issue integrating it in my react-native and create-react-app. I have tried many different solutions but had no luck
`//my package.json
"dependencies": {
"@zeit/next-css": "^1.0.1",
"@zeit/next-sass": "^1.0.1",
"next": "9.2.2",
"next-images": "^1.3.1",
"node-sass": "^4.13.1",
"react": "16.12.0",
"react-dom": "16.12.0",
"react-flags-select": "^1.1.10"
},
  "devDependencies": {
    "babel-plugin-inline-react-svg": "^1.1.1"
  }`

How can I make it work with my next.js application

**Comment by vikrantraut** [comment]
Same issue still unsolved.

**Comment by maxgfr** [comment]
+1

**Comment by YousefYasin** [comment]
+1

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 which now renders the flags as SVGs
