### ISSUE TITLE
flags select box initial loading country flag didn't show 

### ISSUE THREAD

**Issue by Sirajul-haq** [ekwonye-richard/react-flags-select#44]
React-flags-select  initial loading country flag didn't show . When I select one region, then the flag showed.

```
import ReactFlagsSelect from 'react-flags-select';
import 'react-flags-select/scss/react-flags-select.scss';

const LocalSelect = () => {

return ( 

 <ReactFlagsSelect
  searchable={true}
  searchPlaceholder="Search"
  className="menu-flags"
  defaultCountry="US"
  showSelectedLabel={true} />     

 )
}

```
![Screenshot_2020-03-12 React App](https://user-images.githubusercontent.com/58596461/76621516-8e2a8c00-6555-11ea-93eb-9ab4274511fe.png)

**Comment by ekwonye-richard** [comment]
`defaultCountry` has be removed in v2 and replaced with `selected` which is a more stable approach
