### ISSUE TITLE
ModuleNotFoundError in CodeSandBox

### ISSUE THREAD

**Issue by AnthonyDaSilvaFe** [ekwonye-richard/react-flags-select#45]
Hi,

I added the dependency in CodeSandbox and I have the following error :

ModuleNotFoundError
Could not find module in path: 'react-flags-select/flags/us.svg' relative to '/node_modules/react-flags-select/lib/index.js'

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 🙏🏾
