### ISSUE TITLE
react-flags-select submits the form onchange

### ISSUE THREAD

**Issue by SenikFarsyan** [ekwonye-richard/react-flags-select#46]
i am using it in a form , when trying to select country it submits te form

**Comment by akash-int** [comment]
Hi @ekwonye-richard @SenikFarsyan 
I'm also facing the same issue while changing the dropdown value. The form is submitting automatically. Can anyone please help me out?

Thanks in advance.

**Comment by WoNd3RBoY** [comment]
Why was this issue closed? Has anyone found a solution or are we missing something?

**Comment by thomasdseao** [comment]
I got an error when installing (The prepack command) : Cannot copy `umd/main.css`: the file doesn't exist
