### ISSUE TITLE
Very poor vertical alignment

### ISSUE THREAD

**Issue by luisggouveia** [ekwonye-richard/react-flags-select#48]
Very poor vertical alignment:

![image](https://user-images.githubusercontent.com/6490842/81674017-75026680-9444-11ea-90ea-b11316d5ba76.png)

Can you please fix it?

**Comment by Hadjimina** [comment]
I just created a PR for it. #66 should fix it.

Alternatively just remove the `top: 0.3em` in the css file in the 
`.flag-select__option__icon` class

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 🙏🏾
