### ISSUE TITLE
react-flags-select submits the form onchange

### ISSUE THREAD

**Issue by samw2k00** [ekwonye-richard/react-flags-select#49]
when adding the component inside the form, when clicked on the dropdown it automatically submit the form. How do we prevent this

**Comment by thomasdseao** [comment]
I got an error when installing (The prepack command) : Cannot copy umd/main.css: the file doesn't exist

**Comment by samw2k00** [comment]
@thomasdseao thank you for your feedback, when I did the fork, the main.css already missing. The pull request is only to fix the auto submit when using this in a form!
