### ISSUE TITLE
searchable={true} doesnt work

### ISSUE THREAD

**Issue by andredicioccio** [ekwonye-richard/react-flags-select#5]
Hi there,
Great component firstly.  I am wondering if there is any reason that searchable={true} would not be working for me?
I have tried inspecting the HTML and it doesnt look like it is being generated.

**Comment by newbreedofgeek** [comment]
I have the same problem, I think it may be due to the fact that this has a react peer dependency of 15.x. In my case I had react 16.2.0

**Comment by ekwonye-richard** [comment]
@andredicioccio @newbreedofgeek Thanks for the feedback, the feature has been updated. Kindly update to the latest version on npm.
