### ISSUE TITLE
After closing the dropdown searchable field is not getting cleared

### ISSUE THREAD

**Issue by developer-akash** [ekwonye-richard/react-flags-select#55]
after searching any country from the list if I don't select the country & close the dropdown country remains on the list.

In the attached example see I have searched for Cuba & close the dropdown without selecting Cuba from the list. After that again when I open the list search field is cleared but the list is not updated.
![Screen Shot 2020-06-11 at 11 34 17 AM](https://user-images.githubusercontent.com/39612216/84350739-82dc1080-abd7-11ea-8360-0ecd0d07ee2b.png)

Thanks in advance!

**Comment by iamacoderguy** [comment]
The same here. Any suggestion?

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 🙏🏾
