### ISSUE TITLE
Using string ref is discouraged

### ISSUE THREAD

**Issue by colthreepv** [ekwonye-richard/react-flags-select#56]
Including this library in a modern version of React recites so:

> A string ref, "selectedFlag", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided. We recommend using useRef() or createRef() instead. Learn more about using refs safely here: https://fb.me/react-strict-mode-string-ref

**Comment by ekwonye-richard** [comment]
We are no longer using refs in v2 🙏🏾
