### ISSUE TITLE
Showing multiple times the same flag for different locales

### ISSUE THREAD

**Issue by zedtux** [ekwonye-richard/react-flags-select#61]
I'm trying to so a language selector using this component but the issue is that for the same country, there are different languages, but only the last one is kept from the `customLabels` object.

Here is how I'm trying to use `customLabels`:

```javascript
<ReactFlagsSelect
  countries={['BE', 'FR']}
  customLabels={{
    BE: 'FR',
    BE: 'NL',
    FR: 'FR'
  }}
/>
```

Would you mind to implement this use case please?

---

Adding another `BE` in the `countries` list helped a little bit:

```javascript
<ReactFlagsSelect
  countries={['BE', 'BE', 'FR']}
  customLabels={{
    BE: 'FR',
    BE: 'NL',
    FR: 'FR'
  }}
/>
```

![Screenshot 2020-10-26 at 16 23 28](https://user-images.githubusercontent.com/478564/97191846-96170380-17a7-11eb-9017-3b3bb7682683.png)

**Comment by zedtux** [comment]
A better option would be to allow passing an array of string or an Object as `countries` and remove the `customLabels`:

```javascript
<ReactFlagsSelect
  countries={{
    BE: 'FR',
    BE: 'NL',
    FR: 'FR'
  }}
/>
```

It would cover the `README.md` example too:

```javascript
<ReactFlagsSelect
  countries={{
    US: 'EN-US',
    GB: 'EN-GB,
    FR: 'FR',
    DE: 'DE',
    IT: 'IT'
  }}
/>
```

**Comment by Filip785** [comment]
I'm looking for exactly the same thing. Another use case: some languages can be written in multiple alphabets, for example Serbian language can be written with both latin and cyrillic alphabets, thus this would be useful.

Hope this can be merged soon.

**Comment by zedtux** [comment]
Great to see that my work would help someone else ! 🤩

**Comment by zedtux** [comment]
@ekwonye-richard can you please have a look at [the PR](https://github.com/ekwonye-richard/react-flags-select/pull/63) and give your input?

**Comment by ekwonye-richard** [comment]
Closing this following the closed [PR](https://github.com/ekwonye-richard/react-flags-select/pull/63)
