### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by yoanndelattre** [ekwonye-richard/react-flags-select#65]
The images of the flags are missing.

![Capture web](https://user-images.githubusercontent.com/32218722/97806821-da018100-1c5d-11eb-93af-54b611bf17a2.png)
![code](https://user-images.githubusercontent.com/32218722/97806822-da018100-1c5d-11eb-93ae-6506b191daa0.png)
![inspect](https://user-images.githubusercontent.com/32218722/97807312-614ff400-1c60-11eb-9892-3f61521a94ca.png)

**Comment by aakanshu** [comment]
@yoanndelattre I'm facing the same issue on upgrading my react-scripts to version 4 (`"react-scripts": "^4.0.1"` ).
For version 3 it is working fine. If possible try downgrading react-script and try.

**Comment by yoanndelattre** [comment]
Ok, I demoted react-scripts to version 3.4.4 and it works!
We'll still have to see what the problem is.
Do I have to close this issue?

**Comment by aakanshu** [comment]
@yoanndelattre let it be open, as it is a temporary fix for now. If you inspect the broken image you can see it is not getting path correctly.

**Comment by hmadhsan** [comment]
Downgrade react-scripts to version 3.4.4 works for me!

**Comment by ekwonye-richard** [comment]
This issue has been resolved in v2 which now renders the flags as SVGs
