### ISSUE TITLE
How to add AutoComplete attribute in input of dropdown

### ISSUE THREAD

**Issue by MohsinBaig101** [ekwonye-richard/react-flags-select#79]
i am trying to customize input but i did't find a way, how to add custom attribute in dropdown input.

**Comment by ekwonye-richard** [comment]
@MohsinBaig101 have you tried the `searchable` props? Does it achieve what you want?

**Comment by ekwonye-richard** [comment]
What kind of custom attribute are you referring to?

**Comment by MohsinBaig101** [comment]
searchable its just a flag, but i want to off autofill in country input

**Comment by MohsinBaig101** [comment]
browser cache data is showing in country input, and i want to turn off

**Comment by MohsinBaig101** [comment]
like
<input name="q" type="text" autocomplete="off"/>

How we add html5 attribute in country input

**Comment by MohsinBaig101** [comment]
@ekwonye-richard ?

**Comment by ekwonye-richard** [comment]
Oh snap! I can expose a prop for the searchInput attributes and by default set autoComplete to `off`.
I'll push this changes to v2.

**Comment by MohsinBaig101** [comment]
@ekwonye-richard when you will push v2 ?

**Comment by ekwonye-richard** [comment]
v2 has been pushed @MohsinBaig101

**Comment by ekwonye-richard** [comment]
We can close this issue now, let me know if you have any issues
