### ISSUE TITLE
Search field is case sensitive

### ISSUE THREAD

**Issue by CristiMD** [ekwonye-richard/react-flags-select#95]
As of right now, the search option looks for identical strings, so searching for "france" returns nothing while searching for "France" returns the right option. Is it possible to make the search case insensitive?

**Comment by krupal1710** [comment]
Yes I also face the same issue

**Comment by ekwonye-richard** [comment]
Hi @CristiMD @krupal1710 thanks for reporting this bug. The fix has been pushed in the latest version
